import sys
from pathlib import Path

# Ensure project root is in sys.path when running script directly
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from llm_client import create_llm, safe_invoke


def report_agent(
    topic,
    research_result,
    web_sources,
    literature_analysis,
    literature_sources,
    critic_result,
    evidence,
    verification_results=None,
):
    """Generate the final research report with verified source lists."""

    llm = create_llm()

    # =========================================
    # GENERAL WEB SOURCES — GENERATED BY PYTHON
    # =========================================

    if web_sources:

        general_sources = "\n".join(
            f"{i + 1}. {source.get('title', 'Untitled')}\n"
            f"   URL: {source.get('url', '')}"
            for i, source in enumerate(web_sources)
        )

    else:

        general_sources = (
            "No general web sources were found."
        )

    # =========================================
    # ACADEMIC SOURCES — GENERATED BY PYTHON
    # =========================================

    if literature_sources:

        academic_sources = "\n".join(
            f"{i + 1}. {source.get('title', 'Untitled')}\n"
            f"   URL: {source.get('url', '')}"
            for i, source in enumerate(literature_sources)
        )

    else:

        academic_sources = (
            "No academic sources were found."
        )

    citation_sources = []
    citation_numbers = {}
    evidence_sections = []

    for item in evidence:
        source_url = item.get("source_url", "").strip()

        if not source_url:
            continue

        if source_url not in citation_numbers:
            citation_numbers[source_url] = len(citation_sources) + 1
            citation_sources.append({
                "title": item.get("source_title", "Untitled"),
                "url": source_url,
            })

        citation_number = citation_numbers[source_url]
        evidence_sections.append(
            f"CITATION [{citation_number}]\n"
            f"SOURCE_ID: {item.get('source_id', '')}\n"
            f"TITLE: {item.get('source_title', '')}\n"
            f"URL: {source_url}\n\n"
            f"EVIDENCE:\n{item.get('evidence', '')}\n\n"
            f"CLAIM:\n{item.get('claim', '')}"
        )

    evidence_information = "\n\n".join(evidence_sections)

    if not evidence_information:

        evidence_information = (
            "No extracted evidence was available."
        )

    # =========================================
    # UNVERIFIED CLAIMS (Verification Node)
    # =========================================
    
    unverified_section = ""
    if verification_results:
        from agents.verification_agent import get_unverified_claims, CONTRADICTION
        unverified_claims = get_unverified_claims({"results": verification_results})
        
        if unverified_claims:
            unverified_section = "\n\n### Claims We Could Not Verify\n\n"
            unverified_section += "The following claims were extracted from sources but our NLI verification model could not confirm that the source text directly entails them. These should be treated with additional scrutiny:\n\n"
            
            for uc in unverified_claims:
                icon = "❌" if uc["label"] == CONTRADICTION else "⚠️"
                conf = f" (confidence: {uc['confidence']})" if uc['confidence'] else ""
                
                # Try to link it to the citation number if possible
                cit_num = ""
                for k, v in citation_numbers.items():
                    if uc["source_url"] == k:
                        cit_num = f"[{v}] "
                        break
                        
                unverified_section += f"- {icon} \"{uc['claim']}\"\n"
                unverified_section += f"  Source: {cit_num}[{uc['source_title']}]({uc['source_url']}) | Status: {uc['label']}{conf}\n\n"

    # =========================================
    # REPORT PROMPT
    # =========================================

    prompt = f"""
You are the final report-writing agent.

Research topic:
{topic}

========================================
GENERAL WEB RESEARCH
========================================

{research_result}

========================================
LITERATURE ANALYSIS
========================================

{literature_analysis}

---

## Unverified Claims Data
If there are unverified claims, include them exactly as provided below inside your "5. Knowledge Gaps" section. Do not alter them.
{unverified_section}

---

## 4. INSTRUCTIONS
========================================
CRITIC REPORT
========================================

{critic_result}

========================================
EVIDENCE AND SUPPORTED CLAIMS
========================================

{evidence_information}

========================================
TASK
========================================

Write ONLY the main body of the research report.

Use exactly these sections:

# Research Report

## 1. Executive Summary

## 2. General Research Findings

## 3. Literature Review

## 4. Critical Analysis

## 5. Knowledge Gaps

## 6. Recommendations

## 7. Conclusion

Do NOT create:

- Section 8
- Section 9
- a References section
- a bibliography
- a source list

Those sections will be created separately by Python.

========================================
SECTION RULES
========================================

### Executive Summary

Summarize:

- the research topic
- major findings
- major challenges
- overall conclusion

Keep it concise.

### General Research Findings

Discuss findings from the general web research.

Do not turn this section into a literature review.

Use only information supported by the research.

### Literature Review

Discuss the academic literature provided.

For important sources discuss:

- research focus
- key findings, if available
- limitations, if available

Do not invent:

- authors
- dates
- DOI numbers
- findings
- limitations

If information is unavailable, say:

"Not enough information was available."

### Critical Analysis

Evaluate the evidence rather than simply
repeating the literature review.

Discuss:

- strengths
- weaknesses
- source-quality concerns
- missing information
- contradictions, if actually supported

### Knowledge Gaps

Identify specific unanswered questions.

Avoid vague statements such as:

"More research is needed."

Explain exactly what information is missing.

### Recommendations

Give recommendations that directly address
the identified knowledge gaps.

### Conclusion

Summarize the report.

Do not introduce new information.

========================================
IMPORTANT
========================================

IMPORTANT EVIDENCE RULES

Use the evidence provided above to support
factual claims.

Do not create factual claims that are not
supported by the provided evidence.

If a claim cannot be supported by the
available evidence, do not present it as
established fact.

Use the citation number shown beside each evidence item.
Place its marker directly after each supported claim,
for example: "AI can assist diagnosis [1]."
Use a citation only for the specific claim it supports;
do not cite an entire paragraph when claims have different sources.
Do not cite every sentence unless the evidence supports it.
Do not invent citation numbers or URLs.

When making an evidence-supported claim,
associate it with the source that supplied
the evidence.

Do not invent sources.

Do not invent facts.

Do not invent authors.

Do not invent publication dates.

Do not invent DOI numbers.

Do not create a bibliography.

Do not create Section 8 or Section 9.

Do not repeat the same content unnecessarily.

Use only the information provided above.

Return ONLY Sections 1 through 7.
"""

    # =========================================
    # WRITE REPORT VIA LLM
    # =========================================

    fallback_body = (
        "# Research Report\n\n"
        "## 1. Executive Summary\n\n"
        "The report body could not be generated due to an LLM "
        "error. Raw research materials are included below.\n\n"
        "## 2. General Research Findings\n\n"
        f"{research_result or 'No general research was collected.'}\n\n"
        "## 3. Literature Review\n\n"
        f"{literature_analysis or 'No literature analysis was generated.'}\n\n"
        "## 4. Critical Analysis\n\n"
        f"{critic_result or 'No critique was generated.'}\n\n"
        "## 5. Knowledge Gaps\n\n"
        "Not enough information was available.\n\n"
        "## 6. Recommendations\n\n"
        "Re-run the report generation step once the LLM service "
        "is available.\n\n"
        "## 7. Conclusion\n\n"
        "This report is incomplete due to a report-generation "
        "failure."
    )

    report_body = safe_invoke(
        llm,
        prompt,
        default=fallback_body
    )

    # =========================================
    # APPEND PYTHON-VERIFIED CITATIONS
    # =========================================

    if citation_sources:
        sources_section = "\n".join(
            f"[{index}] [{source['title']}]({source['url']})"
            for index, source in enumerate(citation_sources, start=1)
        )
    else:
        sources_section = "No cited sources were available."

    final_report = (
        report_body
        + "\n\n"
        + "### Sources\n\n"
        + sources_section
    )

    return final_report